name: Use Custom Echo Hello Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Echo Hello Action
      uses: ./.github/actions/echo-hello
      with:
        rts: ${{ "Mathi" }}
